name = "voxyl-api"
main = "src/index.ts"
compatibility_date = "2026-07-07"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "api.voxyl.renbrant.com", custom_domain = true }
]

[vars]
CLERK_AUTHORIZED_PARTIES = "http://127.0.0.1:5173,http://localhost:5173,https://voxyl.renbrant.com,https://v.renbrant.com"
CLERK_ISSUER = "https://clerk.v.renbrant.com"

[[d1_databases]]
binding = "DB"
database_name = "voxyl-db"
database_id = "7f54b56f-9df1-4c12-b685-9fc7af29f094"

[[kv_namespaces]]
binding = "VOXYL_CACHE"
id = "f343ebdd13a74e0881985824de684671"

[[r2_buckets]]
binding = "VOXYL_MEDIA"
bucket_name = "voxyl-media"
